base_path:
    base_output_path: /mnt/hwfile/llmrazor/qa-llm-cicd/test_output
    base_baseline_path: /mnt/hwfile/llmrazor/qa-llm-cicd/xtuner_baselines/latest

default_config:
    train: 
        resource:
            gpus_per_task: 16
            cpus_per_task: 256
            memory_per_task: 1920
            image: ccr-hw/910c:cann852-qwen35-0610
            pip_package: pip install -e . --no-deps
    eval:
        resource:
            gpus_per_task: 0
            cpus_per_task: 16
            memory_per_task: 128
            image: ailab-puyu/auto-eval:ld_0101_oc_8ee07ac_v3
            envs: 
                - HF_HUB_CACHE=/mnt/shared-storage-user/auto-eval-pipeline/opencompass/models/hf_hub
                - HF_DATASETS_CACHE=/mnt/shared-storage-user/auto-eval-pipeline/opencompass/llmeval/hf_cache
                - COMPASS_DATA_CACHE=/mnt/shared-storage-user/auto-eval-pipeline/opencompass/llmeval/compass_data_cache
                - HF_DATASETS_OFFLINE=1
                - HF_HUB_OFFLINE=1

case: 
    npu-qwen35-sft-test:
        -
            type: sft
            parameters:
                output_path: /mnt/hwfile/llmrazor/qa-llm-cicd/test_output
            resource:
                num_nodes: 2
                cpus_per_task: 256
                envs:
                    - PIP_INDEX_URL=http://pkg.pjlab.org.cn/repository/pypi-tsinghua/simple
                    - PIP_TRUSTED_HOST=pkg.pjlab.org.cn
            assert_info:
                base_metric: npu-qwen35-sft-test/tracker.jsonl
                check_metrics:
                    grad_norm: 0.000001
                    loss/reduced_llm_loss: 0.000001
                    lr: 0
                    memory/max_memory_GB: 0.2
                    runtime_info/tgs: 0.05
                    runtime_info/text_tokens: 0
            timeout: 10800

