[pytest]
python_files = test*_*.py  # test file
python_classes = Test*     # test class
python_functions = test_*  # test function
pytest_runtest_call.tryfirst = True
filterwarnings = ignore::UserWarning
reruns = 0
reruns_delay = 1
# Parallel ETE: pytest -n 4 -m all
addopts = -p no:cacheprovider
markers =
    all: run all ETE cases via test_all
    rl: RL ETE cases
    sft: SFT ETE cases
    pre_train: pretrain ETE cases
