CUDA_VISIBLE_DEVICES=1,2,3,4 torchrun --nproc_per_node=4 --master_port=10000 train_alpaca-qlora_with_mmchat_hf.py \
    --model_name_or_path internlm/internlm-7b \
    --use_qlora True \
    --use_lora False \
    --bf16 True \
    --output_dir work-dirs/mmchat_hf_internlm-7b_qlora \
    --num_train_epochs 3 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 1 \
    --learning_rate 2e-5 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --remove_unused_columns False \
    --ddp_find_unused_parameters False
