#!/usr/bin/env bash

set -euo pipefail

TEACHER_MODEL_PATH=${1:?"Usage: $0 TEACHER_MODEL_PATH"}
TEACHER_HOST=${TEACHER_HOST:-127.0.0.1}
TEACHER_PORT=${TEACHER_PORT:-13141}
TEACHER_TP_SIZE=${TEACHER_TP_SIZE:-1}
TEACHER_CHUNKED_PREFILL_SIZE=${TEACHER_CHUNKED_PREFILL_SIZE:-4096}
TEACHER_GPU_MEMORY_UTILIZATION=${TEACHER_GPU_MEMORY_UTILIZATION:-0.6}
PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE:-python}

exec "${PYTHON_EXECUTABLE}" -m sglang.launch_server \
    --model-path "${TEACHER_MODEL_PATH}" \
    --host "${TEACHER_HOST}" \
    --port "${TEACHER_PORT}" \
    --tp "${TEACHER_TP_SIZE}" \
    --chunked-prefill-size "${TEACHER_CHUNKED_PREFILL_SIZE}" \
    --mem-fraction-static "${TEACHER_GPU_MEMORY_UTILIZATION}"
