# Copyright (c) OpenMMLab. All rights reserved.
IGNORE_INDEX = -100
DEFAULT_PAD_TOKEN_INDEX = 0
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = '<image>'
DEFAULT_AUDIO_TOKEN = '<audio>'
LLAST_AUDIO_TOKEN_INDEX = -300  # for LLaST
LLAST_AUDIO_PADDING_TOKEN_INDEX = 1000  # padding token for LLaST
